import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { OwnerAccess } from "@/components/OwnerAccess";
import { OwnerDashboard } from "@/components/OwnerDashboard";
import { query } from "@/lib/db";
import { config } from "@/lib/config";
import { getManagedProduct } from "@/lib/product-data";
import { currentUserFromHeaders } from "@/lib/auth";

export const dynamic = "force-dynamic";
export default async function ManagePage({ params, searchParams }: PageProps<"/manage/[slug]"> & { searchParams: Promise<{ tab?: string }> }) {
  const [{ slug }, queryParams] = await Promise.all([params, searchParams]); const product = await getManagedProduct(slug); if (!product) notFound();
  const user = await currentUserFromHeaders(await headers()).catch(() => null);
  const accountOwner = user ? (await query<{ allowed: boolean }>(`SELECT EXISTS(SELECT 1 FROM product_owners WHERE product_id=$1::uuid AND user_id=$2) OR EXISTS(SELECT 1 FROM products WHERE id=$1::uuid AND created_by_user_id=$2) AS allowed`, [product.id, user.id]))[0]?.allowed : false;
  if (!accountOwner) return <main className="app-shell inner-page"><OwnerAccess slug={slug} /></main>;
  const [clicks,evidence,integrations,growthRows,workspaceUpdates,review,categories] = await Promise.all([query<{ count: string }>(`SELECT count(*)::text AS count FROM product_outbound_click_events WHERE product_id=$1::uuid AND outcome='counted'`, [product.id]),query<{id:string;metric_type:string;evidence_url:string;note:string|null;status:string}>(`SELECT id::text,metric_type,evidence_url,note,status FROM product_public_evidence WHERE product_id=$1::uuid ORDER BY submitted_at DESC`,[product.id]),query<{public_id:string;allowed_domain:string;verification_token:string;domain_status:string;domain_verified_at:Date|null;domain_last_checked_at:Date|null;domain_check_outcome:string|null;verification_method:"meta"|"file";badge_status:string;badge_installed_at:Date|null;badge_last_checked_at:Date|null;badge_last_seen_at:Date|null;last_visitor_event_at:Date|null;product_verified_at:Date|null;last_event_at:Date|null;has_secret:boolean}>(`SELECT public_id::text,allowed_domain,verification_token,domain_status,domain_verified_at,domain_last_checked_at,domain_check_outcome,verification_method,badge_status,badge_installed_at,badge_last_checked_at,badge_last_seen_at,last_visitor_event_at,product_verified_at,last_event_at,(secret_hash IS NOT NULL) AS has_secret FROM product_integrations WHERE product_id=$1::uuid`,[product.id]),query<{listing_views:number;outbound_clicks:number;followers:number;comments:number;launch_votes:number}>(`SELECT
    (SELECT count(*)::int FROM product_listing_view_events WHERE product_id=$1::uuid AND outcome='counted') AS listing_views,
    (SELECT count(*)::int FROM product_outbound_click_events WHERE product_id=$1::uuid AND outcome='counted') AS outbound_clicks,
    (SELECT count(*)::int FROM product_follows WHERE product_id=$1::uuid) AS followers,
    (SELECT count(*)::int FROM product_comments WHERE product_id=$1::uuid AND hidden_at IS NULL) AS comments,
    (SELECT count(*)::int FROM launch_votes lv JOIN product_launches pl ON pl.id=lv.launch_id WHERE pl.product_id=$1::uuid AND lv.active) AS launch_votes`,[product.id]),query<{id:string;type:string;title:string;body:string;link_url:string|null;status:"draft"|"published"|"archived";published_at:Date|null;updated_at:Date}>(`SELECT id::text,type,title,body,link_url,status,published_at,updated_at FROM product_updates WHERE product_id=$1::uuid ORDER BY updated_at DESC,id DESC`,[product.id]),query<{internal_reason:string|null}>(`SELECT internal_reason FROM product_moderation_events WHERE product_id=$1::uuid AND to_status='rejected' ORDER BY created_at DESC LIMIT 1`,[product.id]),query<{id:string;name:string}>(`SELECT id::text,name FROM categories WHERE slug=ANY($1::text[]) ORDER BY name`,[["ai-tools","productivity","developer-tools","marketing-seo","sales-crm","design-creative","writing-content","analytics-data","finance-accounting","ecommerce","education","health-fitness","travel","games","directories-discovery","advertising-sponsorship","other"]])]);
  const { ownerTokenHash: _, ownerTokenVersion: __, ...safeProduct } = product; void _; void __;
  const integration=integrations[0];const initial=integration?{publicId:integration.public_id,allowedDomain:integration.allowed_domain,verificationToken:integration.verification_token,domainStatus:integration.domain_status,domainVerifiedAt:integration.domain_verified_at?.toISOString()??null,domainLastCheckedAt:integration.domain_last_checked_at?.toISOString()??null,domainCheckOutcome:integration.domain_check_outcome,verificationMethod:integration.verification_method,badgeStatus:integration.badge_status,badgeInstalledAt:integration.badge_installed_at?.toISOString()??null,badgeLastCheckedAt:integration.badge_last_checked_at?.toISOString()??null,badgeLastSeenAt:integration.badge_last_seen_at?.toISOString()??null,lastVisitorEventAt:integration.last_visitor_event_at?.toISOString()??null,productVerifiedAt:integration.product_verified_at?.toISOString()??null,lastEventAt:integration.last_event_at?.toISOString()??null,hasSecret:integration.has_secret}:null;
  const initialTab=queryParams.tab==="updates"?"updates":queryParams.tab==="verification"?"verification":"product";
  const growth=growthRows[0]??{listing_views:0,outbound_clicks:0,followers:0,comments:0,launch_votes:0};
  return <main className="app-shell inner-page manage-page"><OwnerDashboard product={safeProduct} categories={categories} workspaceUpdates={workspaceUpdates.map(item=>({id:item.id,type:item.type,title:item.title,body:item.body,linkUrl:item.link_url,status:item.status,publishedAt:item.published_at?.toISOString()??null,updatedAt:item.updated_at.toISOString()}))} outboundClicks={Number(clicks[0]?.count ?? 0)} growth={{listingViews:growth.listing_views,outboundClicks:growth.outbound_clicks,followers:growth.followers,comments:growth.comments,launchVotes:growth.launch_votes}} evidence={evidence.map(item=>({id:item.id,metricType:item.metric_type,url:item.evidence_url,note:item.note,status:item.status}))} integration={initial} siteUrl={config.siteUrl} initialReviewReason={review[0]?.internal_reason??null} initialTab={initialTab}/></main>;
}
