DROP TABLE IF EXISTS foundertrail_audit_events;
DROP TABLE IF EXISTS sponsor_events;
DROP TABLE IF EXISTS payment_webhook_receipts;
DROP TABLE IF EXISTS sponsor_bookings;
DROP TRIGGER IF EXISTS metric_scope_guard ON metric_connection_scopes;
DROP FUNCTION IF EXISTS foundertrail_guard_metric_scope();
DROP TABLE IF EXISTS metric_connection_scopes;
DROP TABLE IF EXISTS metric_snapshots;
DROP TABLE IF EXISTS metric_connections;
DROP TABLE IF EXISTS notification_jobs;
DROP TABLE IF EXISTS content_reports;
DROP TABLE IF EXISTS product_comments;
DROP TABLE IF EXISTS product_follows;
DROP TABLE IF EXISTS launch_votes;
DROP TABLE IF EXISTS product_launches;
DROP TABLE IF EXISTS launch_weeks;
DROP TABLE IF EXISTS product_claims;
DROP TABLE IF EXISTS product_owners;
ALTER TABLE product_updates DROP COLUMN IF EXISTS archived_at, DROP COLUMN IF EXISTS updated_at, DROP COLUMN IF EXISTS status;
ALTER TABLE product_updates ALTER COLUMN published_at SET NOT NULL;
ALTER TABLE product_updates DROP CONSTRAINT IF EXISTS product_updates_type_check;
ALTER TABLE product_updates ADD CONSTRAINT product_updates_type_check CHECK (type IN ('feature','milestone','launch','announcement'));
ALTER TABLE products DROP COLUMN IF EXISTS pricing_currency, DROP COLUMN IF EXISTS starting_price_minor, DROP COLUMN IF EXISTS pricing_model, DROP COLUMN IF EXISTS intended_audience, DROP COLUMN IF EXISTS use_case, DROP COLUMN IF EXISTS created_by_user_id;
DROP TABLE IF EXISTS auth_verifications;
DROP TABLE IF EXISTS auth_accounts;
DROP TABLE IF EXISTS auth_sessions;
DROP TABLE IF EXISTS app_users;
