import { NextResponse } from "next/server";
import { withTransaction } from "@/lib/db";
import { authenticateOwner } from "@/lib/owner-auth";
import { requestOriginIsSameSite } from "@/lib/request-security";
import { fetchPinnedHttpsText } from "@/lib/safe-fetch";

export async function POST(request:Request,context:RouteContext<"/api/owner/products/[slug]/verify-domain">){if(!requestOriginIsSameSite(request))return NextResponse.json({error:"Invalid origin."},{status:403});const {slug}=await context.params;const owner=await authenticateOwner(request,slug);if(!owner)return NextResponse.json({error:"Owner access required."},{status:401});const rows=await withTransaction(async(client)=>{const found=await client.query<{id:string;allowed_domain:string;verification_token:string}>(`SELECT id::text,allowed_domain,verification_token FROM product_integrations WHERE product_id=$1::uuid`,[owner.productId]);const integration=found.rows[0];if(!integration)throw new Error("NO_INTEGRATION");const recent=await client.query<{count:string}>(`SELECT count(*)::text AS count FROM domain_verification_attempts WHERE integration_id=$1::uuid AND created_at>=now()-interval '1 hour'`,[integration.id]);if(Number(recent.rows[0]?.count??0)>=10)throw new Error("RATE");return integration;}).catch((error)=>{throw error;});
  let outcome="network_error";try{const text=await fetchPinnedHttpsText(rows.allowed_domain,"/.well-known/bidindex-verification.txt");outcome=text.trim()===rows.verification_token?"verified":"invalid_response";}catch(error){outcome=error instanceof Error&&error.message==="NOT_FOUND"?"not_found":"network_error";}
  await withTransaction(async(client)=>{await client.query(`INSERT INTO domain_verification_attempts (integration_id,outcome) VALUES ($1::uuid,$2)`,[rows.id,outcome]);await client.query(`UPDATE product_integrations SET domain_status=$2,domain_verified_at=CASE WHEN $2='verified' THEN now() ELSE domain_verified_at END,updated_at=now() WHERE id=$1::uuid`,[rows.id,outcome==="verified"?"verified":"failed"]);});return NextResponse.json({verified:outcome==="verified",outcome},{status:outcome==="verified"?200:422});}
