import type { Metadata } from "next";
import Link from "next/link";
import { headers } from "next/headers";
import { notFound, redirect } from "next/navigation";
import { LaunchScheduler } from "@/components/LaunchScheduler";
import { currentUserFromHeaders } from "@/lib/auth";
import { query } from "@/lib/db";
export const dynamic="force-dynamic";export const metadata:Metadata={title:"Schedule launch",robots:{index:false,follow:false}};
export default async function LaunchPage({params}:PageProps<"/manage/[slug]/launch">){const{slug}=await params;const user=await currentUserFromHeaders(await headers()).catch(()=>null);if(!user)redirect(`/sign-in?returnTo=${encodeURIComponent(`/manage/${slug}/launch`)}`);const rows=await query<{id:string;name:string;status:string;launch_id:string|null;starts_at:Date|null;ends_at:Date|null;launch_state:string|null;final_rank:number|null;final_vote_count:number|null}>(`SELECT p.id::text,p.name,p.status,pl.id::text AS launch_id,lw.starts_at,lw.ends_at,pl.state AS launch_state,pl.final_rank,pl.final_vote_count FROM products p JOIN product_owners po ON po.product_id=p.id AND po.user_id=$2 LEFT JOIN product_launches pl ON pl.product_id=p.id LEFT JOIN launch_weeks lw ON lw.id=pl.launch_week_id WHERE p.slug=$1`,[slug,user.id]);const product=rows[0];if(!product)notFound();return <main className="app-shell inner-page account-page"><header className="page-heading"><p className="eyebrow">Launch · {product.name}</p><h1>Your first FounderTrail launch</h1><p>A first-time upvote cast during the live week counts in both the permanent total and this week&apos;s score. Earlier support stays permanent but does not inflate the weekly score. Paid placement never affects rank.</p><Link className="text-link" href={`/manage/${slug}`}>← Back to dashboard</Link></header><section className="settings-card">{product.launch_id?<><h2>{product.launch_state}</h2><p>{product.starts_at?.toLocaleString("en",{timeZone:"UTC"})} → {product.ends_at?.toLocaleString("en",{timeZone:"UTC"})} UTC</p>{product.final_rank?<p>Final result: #{product.final_rank} with {product.final_vote_count} votes.</p>:null}</>:product.status==="published"?<LaunchScheduler slug={slug}/>:<p>Your product must be approved and public before scheduling a launch.</p>}</section></main>}
