"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ProductLogo } from "./ProductLogo";
import { LaunchScheduler } from "./LaunchScheduler";
import { activationPost, postLength } from "@/lib/launch-policy";
export type ActivationData = { slug: string; name: string; tagline: string; logo: string | null; publicUrl: string; state: "live" | "scheduled" | "listed" | "past"; startsAt: string | null; endsAt: string | null; post: string | null; shareState: string; composerOpened: boolean; isPro: boolean; price: number; available: number; checkoutStatus?: string; checkoutOrder?: string };
export function ActivationWorkspace({ data, kit }: { data: ActivationData; kit: React.ReactNode }) {
  const defaultPost = (date: string) => activationPost(data.name, data.publicUrl, data.state, date);
  const [post, setPost] = useState(data.post ?? defaultPost(data.startsAt ? data.startsAt.slice(0,10) : ""));
  const [dateLabel, setDateLabel] = useState(data.startsAt ?? "");
  const [endLabel, setEndLabel] = useState(data.endsAt ?? "");
  const [shareState, setShareState] = useState(data.shareState);
  const [composerOpened, setComposerOpened] = useState(data.composerOpened);
  const [notice, setNotice] = useState("");
  const [editingLaunch, setEditingLaunch] = useState(false);
  const [saved, setSaved] = useState(true);
  const [fallback, setFallback] = useState("");
  const editedPost = useRef(false);
  useEffect(() => {
    queueMicrotask(() => {
      if (!data.post && !editedPost.current) setPost(activationPost(data.name,data.publicUrl,data.state,data.startsAt ? new Date(data.startsAt).toLocaleDateString([], {month:"short",day:"numeric"}) : ""));
      if (data.startsAt) setDateLabel(new Date(data.startsAt).toLocaleString([], { dateStyle: "long", timeStyle: "short" }) + ` (${Intl.DateTimeFormat().resolvedOptions().timeZone})`);
      if (data.endsAt) setEndLabel(new Date(data.endsAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }));
    });
    void fetch(`/api/owner/products/${data.slug}/activation`, { method: "PATCH", headers: {"content-type":"application/json"}, body: JSON.stringify({event:"viewed"}) });
  }, [data.slug, data.startsAt, data.endsAt, data.post, data.name, data.publicUrl, data.state]);
  async function persist(body: Record<string, unknown>) {
    const response = await fetch(`/api/owner/products/${data.slug}/activation`, { method: "PATCH", headers: {"content-type":"application/json"}, body: JSON.stringify(body) });
    if (!response.ok) throw new Error("Could not save. Your text is still here; please retry.");
  }
  async function savePost() { try { await persist({post}); setSaved(true); setNotice("Post draft saved."); } catch (error) { setNotice((error as Error).message); } }
  async function copy(value: string, link = false) {
    try { await navigator.clipboard.writeText(value); setNotice(link ? "Page link copied." : "Post copied."); if (link) await persist({event:"copy_link"}); }
    catch { setFallback(value); setNotice("Select and copy the text below."); }
  }
  async function mark(state: string) { try { await persist({shareState:state, event:state === "self_reported" ? "shared" : undefined, post}); setShareState(state); setSaved(true); } catch (error) { setNotice((error as Error).message); } }
  const launched = data.state !== "listed";
  const title = data.state === "live" ? `${data.name} is live and launching this week.` : data.state === "scheduled" ? `${data.name}’s page is live. Your launch is scheduled.` : data.state === "past" ? `${data.name} is live. Keep the momentum going.` : `${data.name}’s page is live. Let’s launch it.`;
  return <>
    <header className="activation-hero"><div className="activation-identity"><ProductLogo productName={data.name} productUrl={null} imageUrl={data.logo} className="activation-logo" /><div><p className="eyebrow">Your launch workspace</p><span className={`activation-status is-${data.state}`}><span aria-hidden="true">●</span> {data.state === "scheduled" ? "Page live · launch scheduled" : data.state === "live" ? "Launching this week" : data.state === "past" ? "Page live · past launch" : "Page live · not scheduled"}</span></div></div><h1>{title}</h1><p>{data.state === "scheduled" ? `Launching ${dateLabel}. Share your page now so people can follow along.` : data.state === "listed" ? "Choose when to join the launch list and invite your first supporters." : "Your page is ready. Invite people to try it, leave feedback, and follow your progress."}</p><div className="activation-url"><a href={data.publicUrl} target="_blank" rel="noopener noreferrer">{data.publicUrl.replace(/^https?:\/\//, "")}</a><button type="button" onClick={() => void copy(data.publicUrl, true)}>Copy link</button></div><Link className="text-link" href={`/product/${data.slug}`} target="_blank">View public page ↗</Link></header>
    {data.checkoutStatus ? <p className="manager-notice">Your page and launch are saved. {data.isPro ? "Pro is active." : data.checkoutStatus === "cancelled" ? "Checkout was cancelled. Continue free or try Pro whenever you’re ready." : "Payment is being verified. Pro activates after confirmed payment."} <Link href={`/manage/${data.slug}/pro${data.checkoutOrder ? `?order=${encodeURIComponent(data.checkoutOrder)}` : ""}`}>Check Pro payment status</Link></p> : null}
    <div className="activation-layout"><div className="activation-tasks">
      <section className={`activation-task ${launched ? "is-complete" : "is-current"}`}><div className="activation-task-heading"><span className="task-number">{launched ? "✓" : "1"}</span><div><p className="eyebrow">Step 01</p><h2>Launch your startup</h2></div>{data.state === "scheduled" ? <button className="text-button" onClick={() => setEditingLaunch(!editingLaunch)}>{editingLaunch ? "Close" : "Edit launch"}</button> : null}</div>{launched ? <p className="task-summary">{data.state === "scheduled" ? `Scheduled for ${dateLabel}` : `Launched ${dateLabel}`}{data.state === "live" ? `. This week’s list ends ${endLabel}.` : ""}</p> : null}{!launched || editingLaunch ? <LaunchScheduler slug={data.slug} scheduled={data.state === "scheduled"} initialChoice={data.state === "scheduled" ? "scheduled" : "now"} initialDate={data.startsAt ?? ""} /> : null}</section>
      <section className={`activation-task ${launched && shareState === "todo" ? "is-current" : ""}`}><div className="activation-task-heading"><span className="task-number">{shareState !== "todo" ? "✓" : "2"}</span><div><p className="eyebrow">Step 02 · optional</p><h2>Invite your first supporters</h2></div></div><p>A small introduction can start a useful conversation. Make this post your own.</p><label className="sr-only" htmlFor="activation-post">Your editable post</label><textarea id="activation-post" className="activation-post" rows={7} maxLength={2000} value={post} onChange={event => { editedPost.current = true; setPost(event.target.value); setSaved(false); }} onBlur={() => { if (!saved) void savePost(); }} /><div className="post-draft-tools"><span className={postLength(post)>280 ? "form-error" : "field-help"}>{postLength(post)}/280 · {saved ? "Draft saved" : "Unsaved changes"}</span><button className="text-button" onClick={() => void savePost()}>Save draft</button><button className="text-button" onClick={() => { editedPost.current = true; setPost(defaultPost(data.startsAt ? new Date(data.startsAt).toLocaleDateString([], { month:"short",day:"numeric" }) : "")); setSaved(false); }}>Refresh template</button></div><div className="button-row"><a className={`button ${launched ? "button-primary" : "button-secondary"}`} href={`https://x.com/intent/tweet?${new URLSearchParams({text:post})}`} target="_blank" rel="noopener noreferrer" aria-disabled={postLength(post)>280} onClick={event => { if(postLength(post)>280) {event.preventDefault(); setNotice("Shorten your post to 280 characters before sharing."); return;} setComposerOpened(true); void persist({event:"composer",post}).catch(()=>setNotice("Composer opened. Could not save activity; you can retry saving your draft.")); }}>Share on X ↗</a><button className="button button-secondary" onClick={() => void copy(post)}>Copy post</button><button className="text-button" onClick={() => void copy(data.publicUrl,true)}>Copy page link</button></div><p className="field-help">You review and publish the post on X. {composerOpened ? "Composer opened — posting is not confirmed." : "Sharing is optional."}</p><div className="share-checklist-state">{shareState === "self_reported" ? <span>✓ Shared · marked by you</span> : shareState === "skipped" ? <span>Skipped for now</span> : <><button className="text-button" onClick={() => void mark("self_reported")}>I’ve shared it</button><button className="text-button" onClick={() => void mark("skipped")}>I’ll do this later</button></>}</div></section>
      <section className="activation-task"><div className="activation-task-heading"><span className="task-number">3</span><div><p className="eyebrow">Step 03 · optional</p><h2>Prepare your launch kit</h2></div></div>{data.isPro ? <><p>Edit your graphic, download it, then copy your post and open X. Attach the downloaded image before posting.</p>{kit}</> : <div className="activation-pro-offer"><span className="eyebrow">A little more launch-ready</span><h3>Make your launch ready to share</h3><p>Editable launch graphics, social post drafts, a seven-day results summary, and a Pro badge.</p><div className="button-row"><Link className="button button-secondary" href={`/manage/${data.slug}?tab=launch-kit`}>Preview launch kit</Link><Link className="text-link" href={`/manage/${data.slug}/pro`}>Upgrade to Pro — ${data.price / 100} one time →</Link></div>{data.price === 500 ? <small>{data.available} introductory purchases available at $5; then $9.</small> : null}</div>}</section>
    </div><aside className="activation-aside"><p className="eyebrow">Your next chapter</p><h2>Built it. Launch it.<br />Keep building.</h2><p>Your page stays with you beyond launch week. Share updates, hear from users, and give people a reason to come back.</p><div className="activation-aside-rule"/><p>Publishing, launching and sharing are free. Your progress is saved to your account.</p><Link className="text-link" href={`/manage/${data.slug}`}>Go to dashboard →</Link></aside></div>
    <p className="form-status" role="status">{notice}</p>{fallback ? <textarea aria-label="Copy this text" value={fallback} readOnly onFocus={e=>e.currentTarget.select()} rows={5}/> : null}<footer className="activation-footer"><Link href={`/manage/${data.slug}`}>Go to dashboard</Link><span>Come back whenever you’re ready.</span></footer>
  </>;
}
