"use client";

import { useState } from "react";

type Claim = { id: string; productName: string; domain: string; requesterName: string; requesterEmail: string; method: string;state:"pending"|"disputed"; createdAt: string };
type Report = { id: string; productName: string; authorName: string; body: string; reason: string; createdAt: string };
type LaunchProduct = { id: string; name: string };
type Booking = { id: string; productName: string; status: string; paymentStatus: string; startAt: string; endAt: string; priceMinor: number; currency: string; paymentId: string | null };
type SponsorIncome={currency:string;grossMinor:number;refundedMinor:number;netMinor:number;taxMinor:number};
type SponsorInventory={startsAt:string;available:boolean};
type ClassificationReview={id:string;productName:string;kind:"category"|"pricing";currentValue:string|null;proposedValue:string;reason:string;confidence:string;evidenceUrl:string|null};
type CategoryOption={slug:string;name:string};

async function api(url: string, method: string, body: Record<string, unknown>) {
  const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const result = await response.json() as { error?: string };
  if (!response.ok) throw new Error(result.error ?? "Action failed.");
}

export function AdminFounderTrailOperations({ claims, reports, launchProducts, bookings,sponsorIncome,sponsorInventory,classifications,categories }: { claims: Claim[]; reports: Report[]; launchProducts: LaunchProduct[]; bookings: Booking[];sponsorIncome:SponsorIncome[];sponsorInventory:SponsorInventory[];classifications:ClassificationReview[];categories:CategoryOption[] }) {
  const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  async function run(key: string, task: () => Promise<void>) { setBusy(key); setMessage(""); try { await task(); setMessage("Saved. Refreshing…"); location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Action failed."); setBusy(""); } }
  async function reviewClaim(id: string, action: "approve" | "reject") { const reason = window.prompt(`Reason for ${action}:`); if (!reason) return; await run(`claim-${id}`, () => api(`/api/admin/claims/${id}`, "PUT", { action, reason })); }
  async function reviewReport(id: string, action: "hide" | "dismiss") { await run(`report-${id}`, () => api(`/api/admin/reports/${id}`, "PUT", { action })); }
  async function schedule(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const date = String(data.get("week") ?? ""); const productId = String(data.get("productId") ?? ""); if (!date) return; await run("launch", () => api("/api/admin/launches", "POST", { productId, weekStartsAt: `${date}T00:00:00.000Z` })); }
  async function refund(id: string) { const reason = window.prompt("Document the reason for this full refund:"); if (!reason) return; await run(`refund-${id}`, () => api(`/api/admin/sponsors/${id}/refund`, "POST", { reason })); }
  async function classify(event:React.FormEvent<HTMLFormElement>,id:string){event.preventDefault();const data=new FormData(event.currentTarget);await run(`classification-${id}`,()=>api(`/api/admin/classifications/${id}`,"PUT",{action:"apply",value:String(data.get("value")??"")}));}
  async function dismissClassification(id:string){if(!window.confirm("Keep the current public value and close this review item?"))return;await run(`classification-${id}`,()=>api(`/api/admin/classifications/${id}`,"PUT",{action:"dismiss"}));}
  return <>{message ? <p className="manager-notice" role="status">{message}</p> : null}<section className="admin-ops-section"><h2>Ownership claims</h2>{claims.length ? claims.map((claim) => <article className="admin-op-row" key={claim.id}><div><strong>{claim.productName}</strong><p>{claim.state} · {claim.domain} · {claim.method.replaceAll("_", " ")} · {new Date(claim.createdAt).toLocaleString()}</p><small>{claim.requesterName} · {claim.requesterEmail}</small></div><div>{claim.state==="pending"?<button className="button button-primary" disabled={Boolean(busy)} onClick={() => void reviewClaim(claim.id, "approve")}>Approve manually</button>:null}<button className="button button-secondary" disabled={Boolean(busy)} onClick={() => void reviewClaim(claim.id, "reject")}>{claim.state==="disputed"?"Uphold existing ownership":"Reject"}</button></div></article>) : <div className="quiet-empty">No pending claims.</div>}</section>
    <section className="admin-ops-section"><h2>Category and pricing review</h2><p className="form-hint">Automated evidence is a suggestion. Applying a value marks it as an admin correction, so later enrichment runs cannot overwrite it.</p>{classifications.length?classifications.map(item=><article className="admin-op-row" key={item.id}><div><strong>{item.productName} · {item.kind}</strong><p>Current: {item.currentValue??"Not listed"} · suggested: {item.proposedValue} · {item.confidence} confidence</p><small>{item.reason}</small>{item.evidenceUrl?<p><a className="text-link" href={item.evidenceUrl} target="_blank" rel="noopener noreferrer nofollow">Review evidence ↗</a></p>:null}</div><form className="admin-inline-form" onSubmit={event=>void classify(event,item.id)}><label><span className="sr-only">Correct {item.kind}</span><select name="value" defaultValue={item.proposedValue}>{item.kind==="category"?categories.map(category=><option key={category.slug} value={category.slug}>{category.name}</option>):<><option value="free">Free</option><option value="freemium">Freemium</option><option value="paid">Paid</option><option value="open_source">Open source</option><option value="contact">Contact sales</option><option value="unknown">Unknown</option></>}</select></label><button className="button button-primary" disabled={Boolean(busy)}>Apply correction</button><button className="button button-secondary" type="button" disabled={Boolean(busy)} onClick={()=>void dismissClassification(item.id)}>Keep current</button></form></article>):<div className="quiet-empty">No classifications need review.</div>}</section>
    <section className="admin-ops-section"><h2>Comment and update reports</h2>{reports.length ? reports.map((report) => <article className="admin-op-row" key={report.id}><div><strong>{report.productName} · {report.authorName}</strong><p>“{report.body}”</p><small>Report: {report.reason} · {new Date(report.createdAt).toLocaleString()}</small></div><div><button className="button button-primary" disabled={Boolean(busy)} onClick={() => void reviewReport(report.id, "hide")}>Hide content</button><button className="button button-secondary" disabled={Boolean(busy)} onClick={() => void reviewReport(report.id, "dismiss")}>Dismiss</button></div></article>) : <div className="quiet-empty">No open reports.</div>}</section>
    <section className="admin-ops-section"><h2>Schedule a first launch</h2><form className="admin-inline-form" onSubmit={(event) => void schedule(event)}><label>Approved product<select name="productId" required defaultValue=""><option value="" disabled>Select product</option>{launchProducts.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Monday (00:00 UTC)<input type="date" name="week" required /></label><button className="button button-primary" disabled={Boolean(busy)}>Schedule</button></form><p className="form-hint">Each product has one initial FounderTrail launch. Ranking uses eligible launch votes, then approval time and product ID.</p></section>
    <section className="admin-ops-section"><h2>Sponsorship income</h2><p className="form-hint">Dodo sponsorship receipts are reported separately from startup-connected revenue metrics.</p>{sponsorIncome.length?<div className="admin-health-grid">{sponsorIncome.map(item=><div key={item.currency}><span>{item.currency} gross / refunds / net</span><strong>{(item.grossMinor/100).toFixed(2)} / {(item.refundedMinor/100).toFixed(2)} / {(item.netMinor/100).toFixed(2)}</strong><small>Recorded tax: {(item.taxMinor/100).toFixed(2)}</small></div>)}</div>:<div className="quiet-empty">No paid sponsorship income.</div>}</section>
    <section className="admin-ops-section"><h2>Sponsor availability calendar</h2><p className="form-hint">Each date represents a seven-day placement starting at 00:00 UTC. Availability includes active holds and pending refunds.</p><div className="sponsor-inventory-calendar">{sponsorInventory.map(item=><span className={item.available?"is-available":"is-booked"} key={item.startsAt}><strong>{new Date(item.startsAt).toLocaleDateString()}</strong><small>{item.available?"Available":"Booked / held"}</small></span>)}</div></section>
    <section className="admin-ops-section"><h2>Sponsor bookings and payments</h2>{bookings.length ? <div className="admin-booking-list">{bookings.map((booking) => <article className="admin-op-row" key={booking.id}><div><strong>{booking.productName}</strong><p>{new Date(booking.startAt).toLocaleString()} → {new Date(booking.endAt).toLocaleString()}</p><small>{booking.status.replaceAll("_", " ")} · payment {booking.paymentStatus.replaceAll("_", " ")} · {(booking.priceMinor / 100).toFixed(2)} {booking.currency}</small></div>{booking.paymentId && ["paid","conflict"].includes(booking.paymentStatus) ? <button className="button button-secondary" disabled={Boolean(busy)} onClick={() => void refund(booking.id)}>Full refund</button> : null}</article>)}</div> : <div className="quiet-empty">No sponsorship bookings.</div>}</section></>;
}
