"use client";

import { useState } from "react";

type Claim = { id: string; productName: string; domain: string; requesterName: string; requesterEmail: string; method: string;state:"pending"|"disputed"; createdAt: string; evidence: Record<string, unknown>; challengeExpiresAt: string | null };

/**
 * Claim evidence is operator-facing, so it is rendered from an allowlist rather than
 * dumped. That keeps a future key -- a token, an address, anything sensitive -- from
 * reaching the admin screen just because someone added it to the jsonb column.
 */
const SAFE_EVIDENCE: Record<string, string> = {
  source: "Source",
  domain: "Domain",
  path: "Proof path",
  domain_verified: "Domain verified",
  competing_owner: "Competing owner",
  manual_review_requested: "Manual review requested",
};

function safeEvidence(evidence: Record<string, unknown>): string {
  return Object.entries(SAFE_EVIDENCE)
    .filter(([key]) => evidence[key] !== undefined && evidence[key] !== null && evidence[key] !== false)
    .map(([key, label]) => (evidence[key] === true ? label : `${label}: ${String(evidence[key])}`))
    .join(" · ");
}

/** What proof, if any, currently backs this claim. */
function verificationState(claim: Claim): string {
  if (claim.evidence.domain_verified === true) return "Domain control verified";
  if (claim.method === "legacy_owner_token") return "Legacy management credential accepted";
  if (claim.method === "manual_admin") return "No automatic proof — needs your judgement";
  if (claim.challengeExpiresAt) {
    return new Date(claim.challengeExpiresAt).getTime() > Date.now()
      ? "Domain challenge issued, file not found yet"
      : "Domain challenge expired without proof";
  }
  return "No proof recorded";
}
type Report = { id: string; productName: string; authorName: string; body: string; reason: string; createdAt: string };
type LaunchProduct = { id: string; name: string };
type Booking = { id: string; productName: string; status: string; paymentStatus: string; startAt: string; endAt: string; priceMinor: number; currency: string; paymentId: string | null };
type SponsorIncome={currency:string;grossMinor:number;refundedMinor:number;netMinor:number;taxMinor:number};
type SponsorInventory={startsAt:string;used:number;capacity:number};
type ClassificationReview={id:string;productName:string;kind:"category"|"pricing";currentValue:string|null;proposedValue:string;reason:string;confidence:string;evidenceUrl:string|null};
type CategoryOption={slug:string;name:string};
type ProOrder={id:string;slug:string;productName:string;environment:string;status:string;entitlementStatus:string|null;priceMinor:number;currency:string;paymentId:string|null;paidAt:string|null;refundedMinor:number;disputeState:string|null};
type ProIncome={currency:string;grossMinor:number;refundMinor:number;netMinor:number;taxMinor:number};
type ProGrantProduct={slug:string;name:string;status:"suspended"|"revoked"|null};

async function api(url: string, method: string, body: Record<string, unknown>) {
  const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const result = await response.json() as { error?: string };
  if (!response.ok) throw new Error(result.error ?? "Action failed.");
}

export function AdminFounderTrailOperations({ claims, reports, launchProducts, bookings,sponsorIncome,sponsorInventory,proOrders,proIncome,proGrantProducts,classifications,categories }: { claims: Claim[]; reports: Report[]; launchProducts: LaunchProduct[]; bookings: Booking[];sponsorIncome:SponsorIncome[];sponsorInventory:SponsorInventory[];proOrders:ProOrder[];proIncome:ProIncome[];proGrantProducts:ProGrantProduct[];classifications:ClassificationReview[];categories:CategoryOption[] }) {
  const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  async function run(key: string, task: () => Promise<void>) { setBusy(key); setMessage(""); try { await task(); setMessage("Saved. Refreshing…"); location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Action failed."); setBusy(""); } }
  async function reviewClaim(id: string, action: "approve" | "reject") { const reason = window.prompt(`Reason for ${action}:`); if (!reason) return; await run(`claim-${id}`, () => api(`/api/admin/claims/${id}`, "PUT", { action, reason })); }
  async function reviewReport(id: string, action: "hide" | "dismiss") { await run(`report-${id}`, () => api(`/api/admin/reports/${id}`, "PUT", { action })); }
  async function schedule(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const date = String(data.get("week") ?? ""); const productId = String(data.get("productId") ?? ""); if (!date) return; await run("launch", () => api("/api/admin/launches", "POST", { productId, weekStartsAt: `${date}T00:00:00.000Z` })); }
  async function refund(id: string) { const reason = window.prompt("Document the reason for this full refund:"); if (!reason) return; await run(`refund-${id}`, () => api(`/api/admin/sponsors/${id}/refund`, "POST", { reason })); }
  async function classify(event:React.FormEvent<HTMLFormElement>,id:string){event.preventDefault();const data=new FormData(event.currentTarget);await run(`classification-${id}`,()=>api(`/api/admin/classifications/${id}`,"PUT",{action:"apply",value:String(data.get("value")??"")}));}
  async function dismissClassification(id:string){if(!window.confirm("Keep the current public value and close this review item?"))return;await run(`classification-${id}`,()=>api(`/api/admin/classifications/${id}`,"PUT",{action:"dismiss"}));}
  async function proEntitlement(slug:string,action:"grant"|"revoke"|"restore"){const reason=window.prompt(`Audit reason for ${action}:`);if(!reason)return;await run(`pro-${slug}`,()=>api(`/api/admin/pro/entitlements/${encodeURIComponent(slug)}`,"POST",{action,reason}));}
  async function grantPro(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const slug=String(data.get("slug")??"");const product=proGrantProducts.find(item=>item.slug===slug);if(!product)return;await proEntitlement(slug,product.status?"restore":"grant");}
  async function refundPro(id:string){const reason=window.prompt("Audit reason for this full Pro refund:");if(!reason)return;await run(`pro-refund-${id}`,()=>api(`/api/admin/pro/orders/${id}/refund`,"POST",{reason}));}
  return <>{message ? <p className="manager-notice" role="status">{message}</p> : null}<section className="admin-ops-section"><h2>Ownership claims</h2><p className="form-hint">This is the moderation queue for claim attempts. An empty list means no claim request is waiting — it does not mean claiming is configured correctly. Approving grants management rights without changing the startup’s history, engagement, slug or launch records.</p>{claims.length ? claims.map((claim) => <article className="admin-op-row" key={claim.id}><div><strong>{claim.productName}</strong><p>{claim.state} · {claim.domain} · {claim.method.replaceAll("_", " ")} · {new Date(claim.createdAt).toLocaleString()}</p><small>{claim.requesterName} · {claim.requesterEmail}</small><p className="form-hint">{verificationState(claim)}{safeEvidence(claim.evidence) ? ` · ${safeEvidence(claim.evidence)}` : ""}</p></div><div>{claim.state==="pending"?<button className="button button-primary" disabled={Boolean(busy)} onClick={() => void reviewClaim(claim.id, "approve")}>Approve manually</button>:null}<button className="button button-secondary" disabled={Boolean(busy)} onClick={() => void reviewClaim(claim.id, "reject")}>{claim.state==="disputed"?"Uphold existing ownership":"Reject"}</button></div></article>) : <div className="quiet-empty">No pending claims.</div>}</section>
    <section className="admin-ops-section"><h2>Category and pricing review</h2><p className="form-hint">Automated evidence is a suggestion. <strong>Apply correction</strong> saves an admin-owned override that later enrichment runs cannot overwrite. <strong>Keep current</strong> records the review decision and removes the item from this queue without changing the public value.</p>{classifications.length?classifications.map(item=><article className="admin-op-row" key={item.id}><div><strong>{item.productName} · {item.kind}</strong><p>Current: {item.currentValue??"Not listed"} · suggested: {item.proposedValue} · {item.confidence} confidence</p><small>{item.reason}</small>{item.evidenceUrl?<p><a className="text-link" href={item.evidenceUrl} target="_blank" rel="noopener noreferrer nofollow">Review evidence ↗</a></p>:null}</div><form className="admin-inline-form" onSubmit={event=>void classify(event,item.id)}><label><span className="sr-only">Correct {item.kind}</span><select name="value" defaultValue={item.proposedValue}>{item.kind==="category"?categories.map(category=><option key={category.slug} value={category.slug}>{category.name}</option>):<><option value="free">Free</option><option value="freemium">Freemium</option><option value="paid">Paid</option><option value="open_source">Open source</option><option value="contact">Contact sales</option><option value="unknown">Unknown</option></>}</select></label><button className="button button-primary" disabled={Boolean(busy)}>Apply correction</button><button className="button button-secondary" type="button" disabled={Boolean(busy)} onClick={()=>void dismissClassification(item.id)}>Keep current</button></form></article>):<div className="quiet-empty">No classifications need review.</div>}</section>
    <section className="admin-ops-section"><h2>Comment and update reports</h2>{reports.length ? reports.map((report) => <article className="admin-op-row" key={report.id}><div><strong>{report.productName} · {report.authorName}</strong><p>“{report.body}”</p><small>Report: {report.reason} · {new Date(report.createdAt).toLocaleString()}</small></div><div><button className="button button-primary" disabled={Boolean(busy)} onClick={() => void reviewReport(report.id, "hide")}>Hide content</button><button className="button button-secondary" disabled={Boolean(busy)} onClick={() => void reviewReport(report.id, "dismiss")}>Dismiss</button></div></article>) : <div className="quiet-empty">No open reports.</div>}</section>
    <section className="admin-ops-section"><h2>Schedule a first launch</h2><form className="admin-inline-form" onSubmit={(event) => void schedule(event)}><label>Approved product<select name="productId" required defaultValue=""><option value="" disabled>Select product</option>{launchProducts.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Monday (00:00 UTC)<input type="date" name="week" required /></label><button className="button button-primary" disabled={Boolean(busy)}>Schedule</button></form><p className="form-hint">Each product has one initial FounderTrail launch. Ranking uses eligible launch votes, then approval time and product ID.</p></section>
    <section className="admin-ops-section"><h2>Pro receipts</h2><p className="form-hint">One-time sales only. Gross is captured payment total, refunds are cumulative recorded refunds, and net is gross minus refunds. None of these figures are MRR.</p>{proIncome.length?<div className="admin-health-grid">{proIncome.map(item=><div key={item.currency}><span>{item.currency} gross / refunds / net</span><strong>{(item.grossMinor/100).toFixed(2)} / {(item.refundMinor/100).toFixed(2)} / {(item.netMinor/100).toFixed(2)}</strong><small>Recorded tax: {(item.taxMinor/100).toFixed(2)}</small></div>)}</div>:<div className="quiet-empty">No paid Pro orders.</div>}</section>
    <section className="admin-ops-section"><h2>Pro orders and entitlements</h2><form className="admin-inline-form" onSubmit={event=>void grantPro(event)}><label>Complimentary Pro access<select name="slug" defaultValue="" required><option value="" disabled>Select an eligible startup</option>{proGrantProducts.map(product=><option key={product.slug} value={product.slug}>{product.name}{product.status?` · ${product.status}`:""}</option>)}</select></label><button className="button button-primary" disabled={Boolean(busy)||!proGrantProducts.length}>Grant or restore</button></form><p className="form-hint">Complimentary access is explicit, reasoned, and audited. It does not consume an introductory purchase slot.</p>{proOrders.length?<div className="admin-booking-list">{proOrders.map(order=><article className="admin-op-row" key={order.id}><div><strong>{order.productName}</strong><p>{order.environment} · order {order.status.replaceAll("_"," ")} · entitlement {order.entitlementStatus??"none"} · {(order.priceMinor/100).toFixed(2)} {order.currency}</p><small>{order.paidAt?new Date(order.paidAt).toLocaleString():"Not paid"}{order.refundedMinor?` · refunded ${(order.refundedMinor/100).toFixed(2)}`:""}{order.disputeState?` · dispute ${order.disputeState}`:""}{order.paymentId?` · payment ${order.paymentId}`:""}</small></div><div className="button-row">{order.entitlementStatus==="active"?<button className="button button-secondary" disabled={Boolean(busy)} onClick={()=>void proEntitlement(order.slug,"revoke")}>Revoke</button>:order.entitlementStatus?<button className="button button-secondary" disabled={Boolean(busy)} onClick={()=>void proEntitlement(order.slug,"restore")}>Restore</button>:<button className="button button-secondary" disabled={Boolean(busy)} onClick={()=>void proEntitlement(order.slug,"grant")}>Grant</button>}{order.paymentId&&["paid","partially_refunded","payment_conflict","disputed"].includes(order.status)?<button className="button button-secondary" disabled={Boolean(busy)} onClick={()=>void refundPro(order.id)}>Full refund</button>:null}</div></article>)}</div>:<div className="quiet-empty">No Pro orders.</div>}</section>
    <details className="admin-ops-section settings-card"><summary>Legacy sponsorship obligations</summary><p className="form-hint">New sales and public delivery are disabled. These records remain for historical reconciliation and refunds.</p>{sponsorIncome.length?<div className="admin-health-grid">{sponsorIncome.map(item=><div key={item.currency}><span>{item.currency} gross / refunds / net</span><strong>{(item.grossMinor/100).toFixed(2)} / {(item.refundedMinor/100).toFixed(2)} / {(item.netMinor/100).toFixed(2)}</strong><small>Recorded tax: {(item.taxMinor/100).toFixed(2)}</small></div>)}</div>:null}{bookings.length ? <div className="admin-booking-list">{bookings.map((booking) => <article className="admin-op-row" key={booking.id}><div><strong>{booking.productName}</strong><p>{new Date(booking.startAt).toLocaleString()} → {new Date(booking.endAt).toLocaleString()}</p><small>{booking.status.replaceAll("_", " ")} · payment {booking.paymentStatus.replaceAll("_", " ")} · {(booking.priceMinor / 100).toFixed(2)} {booking.currency}</small></div>{booking.paymentId && ["paid","conflict"].includes(booking.paymentStatus) ? <button className="button button-secondary" disabled={Boolean(busy)} onClick={() => void refund(booking.id)}>Full refund</button> : null}</article>)}</div> : <div className="quiet-empty">No sponsorship bookings.</div>}<p className="form-hint">Legacy calendar records retained: {sponsorInventory.filter(item=>item.used>0).length} upcoming occupied day buckets.</p></details></>;
}
