"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { AudienceReview } from "@/lib/founder-email-audience";

export function CampaignConfirmation({id,audience,scheduledAt,messageClass}:{id:string;audience:AudienceReview;scheduledAt:string|null;messageClass:"marketing"|"transactional"}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function confirm(){setBusy(true);const response=await fetch(`/api/admin/founder-emails/campaigns/${id}/action`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"confirm"})});const body=await response.json();if(!response.ok){setError(body.error??"Could not confirm campaign.");setBusy(false);return}if(!scheduledAt)await fetch(`/api/admin/founder-emails/campaigns/${id}/action`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"send"})});router.push("/admin/founder-emails");router.refresh()}
  return <section className="manager-card campaign-confirm"><h2>Final confirmation</h2><div className="recipient-summary-grid"><span><strong>{audience.selectedCount}</strong><small>Founders selected</small></span><span><strong>{audience.eligibleCount}</strong><small>Eligible</small></span><span><strong>{audience.excludedCount}</strong><small>Excluded</small></span></div>{messageClass==="marketing"?<p><strong>{audience.marketingAudience.eligible} of {audience.marketingAudience.total} founders</strong> can receive growth emails.</p>:<p><strong>Product/owner update:</strong> marketing consent is not required; hard delivery suppressions still apply.</p>}<p>Each eligible founder receives a separate personalized email. Suppressions are checked again immediately before delivery.</p><div className="campaign-review-list"><h3>Final recipients</h3>{audience.recipients.map(item=><article key={item.email}><div><strong>{item.founderName||"Founder not provided"}</strong><span>{item.email}</span></div><div><strong>{item.product.name}</strong>{item.groupedProducts.length>1?<small>One email · also owns {item.groupedProducts.slice(1).map(product=>product.name).join(", ")}</small>:null}</div></article>)}</div>{audience.exclusions.length?<details className="campaign-exclusions" open><summary>Why {audience.excludedCount} founder{audience.excludedCount===1?" was":"s were"} excluded</summary>{audience.exclusions.map((item,index)=><article key={`${item.product.id}-${index}`}><strong>{item.founderName||"Founder not provided"} · {item.product.name}</strong><span>{item.email}</span><small>{item.reasons.join("; ")}</small></article>)}</details>:null}<p>{scheduledAt?`Scheduled for ${new Date(scheduledAt).toLocaleString()}.`:"The campaign will enter the sending queue now."}</p><div className="campaign-actions"><button className="button" onClick={()=>router.back()}>Back to edit</button><button className="button button-primary" disabled={busy||audience.eligibleCount===0} onClick={confirm}>{busy?"Confirming…":"Confirm and send"}</button></div>{error?<p className="form-error">{error}</p>:null}</section>;
}
