"use client";
import { useState } from "react";

type Integration={publicId:string;allowedDomain:string;verificationToken:string;domainStatus:string;lastEventAt:string|null}|null;
export function IntegrationManager({slug,initial,siteUrl}: {slug:string;initial:Integration;siteUrl:string}){const [integration,setIntegration]=useState(initial);const [secret,setSecret]=useState<string|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function setup(action:"create"|"rotate"){if(action==="rotate"&&!confirm("Rotate the integration secret? Existing server event senders will stop working immediately."))return;setBusy(true);setMessage("");const response=await fetch(`/api/owner/products/${encodeURIComponent(slug)}/integration`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action})});const data=await response.json() as {error?:string;publicId?:string;secret?:string|null;message?:string};setBusy(false);if(!response.ok){setMessage(data.error||"Could not configure integration.");return;}setSecret(data.secret??null);setMessage(data.message||"Saved.");if(!integration&&data.publicId)window.location.reload();}
  async function verify(){setBusy(true);const response=await fetch(`/api/owner/products/${encodeURIComponent(slug)}/verify-domain`,{method:"POST"});const data=await response.json() as {verified?:boolean;error?:string;outcome?:string};setBusy(false);setMessage(data.verified?"Domain verified.":data.error||`Verification failed: ${data.outcome}.`);if(data.verified&&integration)setIntegration({...integration,domainStatus:"verified"});}
  if(!integration)return <section className="manager-card integration-setup"><h2>Create the partner integration</h2><p>This generates a public browser identifier and a separate server secret. The server secret is shown once.</p><button className="button button-primary" disabled={busy} onClick={()=>setup("create")}>Create integration</button>{message?<p>{message}</p>:null}</section>;
  const snippet=(style:string)=>`<script async src="${siteUrl}/embed/badge.js" data-project="${integration.publicId}" data-style="${style}"></script>`;
  return <div className="integration-manager"><section className="manager-card"><p className="eyebrow">Integration status</p><h1>{integration.allowedDomain}</h1><dl className="product-facts"><div><dt>Public project ID</dt><dd><code>{integration.publicId}</code></dd></div><div><dt>Domain</dt><dd>{integration.domainStatus}</dd></div><div><dt>Last event</dt><dd>{integration.lastEventAt?new Date(integration.lastEventAt).toLocaleString():"No events yet"}</dd></div></dl></section>
    {secret?<section className="secret-once"><strong>Copy this server secret now</strong><code>{secret}</code><p>It is never stored in recoverable form and will not be shown again.</p></section>:null}{message?<p className="manager-notice">{message}</p>:null}
    <section className="manager-card"><h2>1. Verify the domain</h2><p>Publish this exact value at <code>https://{integration.allowedDomain}/.well-known/bidindex-verification.txt</code>, then run verification.</p><pre>{integration.verificationToken}</pre><button className="button button-secondary" disabled={busy} onClick={verify}>Check domain</button></section>
    <section className="manager-card"><h2>2. Install a badge and visitor tracking</h2><p>The same lightweight script renders the selected badge and reports a privacy-conscious daily unique visitor. Header placement is never required.</p>{["light","dark","compact"].map(style=><div className="snippet-row" key={style}><strong>{style}</strong><pre>{snippet(style)}</pre></div>)}</section>
    <section className="manager-card"><h2>3. Send verified server events</h2><p>Send purchases, bids, and revenue only from your server. See the partner guide for the JSON contract and examples.</p><button className="button button-secondary" disabled={busy} onClick={()=>setup("rotate")}>Rotate server secret</button></section>
  </div>}
