"use client";
/* eslint-disable @next/next/no-img-element -- moderation previews can be arbitrary, untrusted remote metadata URLs */
import { useState } from "react";
import { ApprovalNotice, type ApprovalNoticeData } from "@/components/ApprovalNotifications";
type Category={id:string;name:string};
type Item={id:string;slug:string;name:string;tagline:string;websiteUrl:string;submittedUrl:string;founderName:string|null;contactEmail:string;submittedAt:string;consentAt:string|null;duplicateCount:number;metadata:{status:string;name:string|null;tagline:string|null;logoUrl:string|null;imageUrl:string|null}|null;media:Array<{id:string;kind:string;url:string}>};
export function ModerationList({items,categories}: {items:Item[];categories:Category[]}){
  const [pending,setPending]=useState(items);const [error,setError]=useState("");const [busy,setBusy]=useState("");const [approved,setApproved]=useState<ApprovalNoticeData|null>(null);
  async function decide(item:Item,status:"published"|"rejected",form:HTMLFormElement){setError("");setBusy(item.slug);const data=new FormData(form);const response=await fetch(`/api/admin/products/${encodeURIComponent(item.slug)}/status`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({status,name:data.get("name"),tagline:data.get("tagline"),categoryId:data.get("categoryId"),reason:data.get("reason"),overrideDuplicate:data.get("overrideDuplicate")==="on"})});const result=await response.json().catch(()=>({})) as {error?:string;product?:{slug:string;name:string;publicUrl:string;approvedAt:string};email?:ApprovalNoticeData["email"]};if(response.ok){setPending(values=>values.filter(value=>value.slug!==item.slug));if(status==="published"&&result.product&&result.email)setApproved({...result.product,email:result.email});}else setError(result.error||"Could not update that submission.");setBusy("");}
  return <>{approved?<ApprovalNotice initial={approved}/>:null}{error?<p className="form-error" role="alert">{error}</p>:null}<div className="moderation-list">{pending.length?pending.map(item=><form className="moderation-card" key={item.id} onSubmit={event=>event.preventDefault()}><div className="moderation-details"><div className="moderation-media">{!item.media.some(media=>media.kind==="logo")&&item.metadata?.logoUrl?<img src={item.metadata.logoUrl} alt="Extracted logo preview" referrerPolicy="no-referrer" />:null}{item.media.map(media=><img key={media.id} src={media.url} alt={`${item.name} ${media.kind}`} />)}</div><label>Product name<input name="name" required maxLength={80} defaultValue={item.name}/></label><label>One-line description<input name="tagline" required maxLength={160} defaultValue={item.tagline}/></label><dl><div><dt>Contact email</dt><dd>{item.contactEmail}</dd></div><div><dt>Founder</dt><dd>{item.founderName||"Not provided"}</dd></div><div><dt>Submitted</dt><dd>{new Date(item.submittedAt).toLocaleString()}</dd></div><div><dt>Consent</dt><dd>{item.consentAt?"Confirmed":"Legacy / not recorded"}</dd></div><div><dt>Metadata</dt><dd>{item.metadata?.status??"Manual"} · extracted: {item.metadata?.name||"—"} / {item.metadata?.tagline||"—"}</dd></div></dl><a href={item.submittedUrl} target="_blank" rel="noopener noreferrer nofollow">Open original URL safely ↗</a></div><div className="moderation-actions"><label>Primary category<select name="categoryId" required>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label>{item.duplicateCount>0?<label className="duplicate-warning"><input type="checkbox" name="overrideDuplicate"/> Approve duplicate domain override ({item.duplicateCount} approved)</label>:null}<label>Internal rejection reason<textarea name="reason" maxLength={1000} rows={3}/></label><button className="button button-secondary" disabled={busy===item.slug} onClick={event=>decide(item,"rejected",event.currentTarget.form!)}>Reject</button><button className="button button-primary" disabled={busy===item.slug} onClick={event=>decide(item,"published",event.currentTarget.form!)}>Approve</button></div></form>):<div className="quiet-empty">No pending submissions.</div>}</div></>}

type RecoveryItem={slug:string;name:string;status:string;contactEmail:string;rotatedAt:string|null};
export function OwnerLinkRecovery({items}:{items:RecoveryItem[]}){
  const [busy,setBusy]=useState("");const [error,setError]=useState("");const [link,setLink]=useState<{slug:string;url:string}|null>(null);const [copied,setCopied]=useState(false);
  async function rotate(item:RecoveryItem){if(!window.confirm(`Create a replacement management link for ${item.name}? The old link will stop working immediately.`))return;setBusy(item.slug);setError("");setLink(null);setCopied(false);const response=await fetch(`/api/admin/products/${encodeURIComponent(item.slug)}/owner-link`,{method:"POST"});const result=await response.json().catch(()=>({})) as {error?:string;managementUrl?:string};if(response.ok&&result.managementUrl)setLink({slug:item.slug,url:result.managementUrl});else setError(result.error||"Could not create a replacement link.");setBusy("");}
  async function copy(){if(!link)return;await navigator.clipboard.writeText(link.url);setCopied(true);}
  return <section className="admin-owner-recovery"><h2>Owner link recovery</h2><p>First verify the founder using the private contact email. Generating a replacement immediately invalidates the old management link.</p>{error?<p className="form-error" role="alert">{error}</p>:null}{link?<div className="private-link-box" aria-live="polite"><strong>Replacement link for {link.slug}</strong><p>Copy it now and send it only to the verified contact. BidIndex stores only its hash.</p><code>{link.url}</code><button className="button button-secondary" type="button" onClick={copy}>{copied?"Copied":"Copy management link"}</button></div>:null}<div className="moderation-list">{items.map(item=><article key={item.slug}><div><h2>{item.name}</h2><p>{item.contactEmail} · {item.status}</p><small>{item.rotatedAt?`Last replaced ${new Date(item.rotatedAt).toLocaleString()}`:"Original link has not been replaced"}</small></div><button className="button button-secondary" type="button" disabled={busy===item.slug} onClick={()=>rotate(item)}>{busy===item.slug?"Generating…":"Generate replacement link"}</button></article>)}</div></section>;
}

type EvidenceItem={id:string;productName:string;metricType:string;url:string;note:string|null;status:string;reviewerNote:string|null;submittedAt:string;reviewedAt:string|null};
export function EvidenceModeration({items}:{items:EvidenceItem[]}){
  const [sources,setSources]=useState(items);const [error,setError]=useState("");const [busy,setBusy]=useState("");
  async function decide(item:EvidenceItem,status:"accepted"|"rejected"|"stale"|"archived",form:HTMLFormElement){setError("");setBusy(item.id);const data=new FormData(form);const response=await fetch(`/api/admin/evidence/${item.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({status,value:data.get("value"),currency:data.get("currency"),reviewerNote:data.get("reviewerNote")})});const result=await response.json().catch(()=>({})) as {error?:string};if(response.ok){if(status==="rejected"||status==="archived")setSources(values=>values.filter(value=>value.id!==item.id));else setSources(values=>values.map(value=>value.id===item.id?{...value,status,reviewerNote:String(data.get("reviewerNote")||"")||null,reviewedAt:new Date().toISOString()}:value));}else setError(result.error||"Could not review evidence.");setBusy("");}
  return <section className="admin-evidence"><h2>Public metric sources</h2>{error?<p className="form-error">{error}</p>:null}{sources.length?sources.map(item=><form key={item.id} onSubmit={event=>event.preventDefault()}><strong>{item.productName} · {item.metricType.replaceAll("_"," ")} · {item.status}</strong><a href={item.url} target="_blank" rel="noopener noreferrer nofollow">Inspect public source ↗</a>{item.note?<p>{item.note}</p>:null}{item.status==="pending"?<div className="form-grid"><label>Reviewed integer value <small>Minor units for revenue</small><input name="value" inputMode="numeric" pattern="[0-9]*"/></label>{item.metricType==="revenue"?<label>Currency<input name="currency" maxLength={3} placeholder="USD"/></label>:null}</div>:<p className="form-hint">Last reviewed: {item.reviewedAt?new Date(item.reviewedAt).toLocaleString():"Not recorded"}</p>}<label>Review note<textarea name="reviewerNote" maxLength={1000} rows={2} defaultValue={item.reviewerNote??""}/></label><div>{item.status==="pending"?<><button className="button button-secondary" disabled={busy===item.id} onClick={event=>decide(item,"rejected",event.currentTarget.form!)}>Reject</button><button className="button button-primary" disabled={busy===item.id} onClick={event=>decide(item,"accepted",event.currentTarget.form!)}>Accept as publicly sourced</button></>:<><button className="button button-secondary" disabled={busy===item.id||item.status==="stale"} onClick={event=>decide(item,"stale",event.currentTarget.form!)}>Mark stale</button><button className="button button-secondary" disabled={busy===item.id} onClick={event=>decide(item,"archived",event.currentTarget.form!)}>Archive</button></>}</div></form>):<div className="quiet-empty">No public metric sources need management.</div>}</section>
}
