"use client";

import { useState } from "react";

type Connection = { id: string; accountId: string | null; scopeMode: string; providerProductIds: string[]; publishRevenue: boolean; publishMrr: boolean; status: string; lastSyncedAt: string | null; lastError: string | null };
type StripeProduct = { id: string; name: string; active: boolean };

export function StripeMetricsManager({ slug, configured, initialConnection }: { slug: string; configured: boolean; initialConnection: Connection | null }) {
  const [connection, setConnection] = useState(initialConnection);
  const [secret, setSecret] = useState("");
  const [products, setProducts] = useState<StripeProduct[]>([]);
  const [selected, setSelected] = useState<string[]>([]);
  const [scopeMode, setScopeMode] = useState<"selected_products" | "account_wide">("selected_products");
  const [confirmed, setConfirmed] = useState(false);
  const [publishRevenue, setPublishRevenue] = useState(connection?.publishRevenue ?? false);
  const [publishMrr, setPublishMrr] = useState(connection?.publishMrr ?? false);
  const [busy, setBusy] = useState("");
  const [message, setMessage] = useState("");
  const endpoint = `/api/owner/products/${encodeURIComponent(slug)}/metrics/stripe`;

  async function request(body: Record<string, unknown>) {
    const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json() as { error?: string; warning?: string; products?: StripeProduct[] };
    if (!response.ok) throw new Error(result.error ?? "Request failed.");
    return result;
  }
  async function inspect() { setBusy("inspect"); setMessage(""); try { const result = await request({ action: "inspect", secret }); setProducts(result.products ?? []); setMessage("Restricted access confirmed. Choose the Stripe products that belong to this startup."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not validate the key."); } finally { setBusy(""); } }
  async function connect() { setBusy("connect"); setMessage(""); try { const result = await request({ action: "connect", secret, scopeMode, providerProductIds: selected, confirmAccountWide: confirmed }); setSecret(""); setMessage(result.warning ?? "Stripe connected. Metrics remain private until you choose to publish them."); location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not connect."); } finally { setBusy(""); } }
  async function sync() { setBusy("sync"); setMessage(""); try { await request({ action: "sync" }); setMessage("Sync complete."); location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Sync failed."); } finally { setBusy(""); } }
  async function savePublication() { setBusy("publish"); setMessage(""); const response = await fetch(endpoint, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ publishRevenue, publishMrr }) }); const result = await response.json() as { error?: string }; setMessage(response.ok ? "Publication settings saved." : result.error ?? "Could not save."); if (response.ok && connection) setConnection({ ...connection, publishRevenue, publishMrr }); setBusy(""); }
  async function disconnect() { if (!window.confirm("Disconnect Stripe and permanently remove the stored key and cached metric snapshots?")) return; setBusy("disconnect"); const response = await fetch(endpoint, { method: "DELETE" }); if (response.ok) { setConnection(null); setMessage("Stripe disconnected and its stored key and snapshots were removed."); } else setMessage("Could not disconnect Stripe."); setBusy(""); }

  if (!configured) return <div className="manager-notice">Stripe metrics are unavailable until the administrator sets a 32-byte METRIC_ENCRYPTION_KEY. Your public listing still works normally.</div>;
  if (connection) return <div className="stripe-connection"><dl className="product-facts"><div><dt>Status</dt><dd>{connection.status}</dd></div><div><dt>Stripe account</dt><dd><code>{connection.accountId}</code></dd></div><div><dt>Scope</dt><dd>{connection.scopeMode === "account_wide" ? "Explicitly confirmed account-wide" : `${connection.providerProductIds.length} selected product(s)`}</dd></div><div><dt>Last refresh</dt><dd>{connection.lastSyncedAt ? new Date(connection.lastSyncedAt).toLocaleString() : "Not yet"}</dd></div></dl>{connection.lastError ? <p className="form-error">Last error: {connection.lastError}</p> : null}<div className="metric-publish-controls"><label><input type="checkbox" checked={publishRevenue} onChange={(event) => setPublishRevenue(event.target.checked)} /> Publish trailing-30-day collected revenue</label><label><input type="checkbox" checked={publishMrr} onChange={(event) => setPublishMrr(event.target.checked)} /> Publish current MRR</label><p>Publishing is optional and separate from connecting. Disconnecting removes the stored key and all cached Stripe snapshots.</p></div><div className="button-row"><button className="button button-primary" disabled={Boolean(busy)} onClick={() => void savePublication()}>Save publication</button><button className="button button-secondary" disabled={Boolean(busy)} onClick={() => void sync()}>Refresh now</button><button className="text-button danger-text" disabled={Boolean(busy)} onClick={() => void disconnect()}>Disconnect</button></div>{message ? <p role="status">{message}</p> : null}</div>;
  return <div className="stripe-connect"><p>Use a Stripe <strong>restricted read-only key</strong> with account, products, prices, charges, invoices, and subscriptions read access. Unrestricted <code>sk_</code> keys are rejected.</p><label>Restricted key<input type="password" autoComplete="off" value={secret} onChange={(event) => setSecret(event.target.value)} placeholder="rk_test_… or rk_live_…" /></label><button className="button button-secondary" disabled={!secret || Boolean(busy)} onClick={() => void inspect()}>{busy === "inspect" ? "Checking…" : "Validate and choose scope"}</button>{products.length ? <div className="stripe-scope"><fieldset><legend>Metric scope</legend><label><input type="radio" checked={scopeMode === "selected_products"} onChange={() => setScopeMode("selected_products")} /> Selected Stripe products</label><label><input type="radio" checked={scopeMode === "account_wide"} onChange={() => setScopeMode("account_wide")} /> Entire Stripe account</label></fieldset>{scopeMode === "selected_products" ? <fieldset><legend>Products belonging to this startup</legend>{products.map((product) => <label key={product.id}><input type="checkbox" checked={selected.includes(product.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, product.id] : current.filter((id) => id !== product.id))} /><span>{product.name}<small>{product.id}</small></span></label>)}</fieldset> : <label className="consent-row"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span>I confirm this account-wide revenue belongs to this startup and is not being presented as another product’s revenue.</span></label>}<button className="button button-primary" disabled={Boolean(busy) || (scopeMode === "selected_products" ? !selected.length : !confirmed)} onClick={() => void connect()}>{busy === "connect" ? "Connecting…" : "Connect privately"}</button></div> : null}{message ? <p role="status" className="form-message">{message}</p> : null}<p className="form-hint">Method: collected revenue includes scoped paid invoice lines from the trailing 30 days, net of allocated recorded refunds and excluding tax. MRR monthly-normalises active or trialing recurring list prices; one-time prices, tax, discounts, cancelled, unpaid, incomplete, and past-due subscriptions are excluded. Currencies are never combined.</p></div>;
}
