export const CAMPAIGN_TEMPLATE_KEYS=["product_approved","founding_product","visitor_milestone","verification_reminder","badge_installation_reminder","weekly_founder_results","custom_announcement"] as const;
export type CampaignTemplateKey=typeof CAMPAIGN_TEMPLATE_KEYS[number];
export type MessageClass="transactional"|"marketing";
export const PERSONALIZATION_TOKENS=["founder_name","product_name","product_url","share_x_url","visitor_count","product_views","product_upvotes","product_rank","referred_visitors","verification_url"] as const;
export type PersonalizationToken=typeof PERSONALIZATION_TOKENS[number];
export type PersonalizationValues=Record<PersonalizationToken,string>;
export type CampaignTemplate={key:CampaignTemplateKey;label:string;messageClass:MessageClass;productSpecific:boolean;subject:string;previewText:string;heading:string;body:string;includeProductLogo:boolean;primaryButtonLabel:string;primaryButtonUrl:string;secondaryButtonLabel:string;secondaryButtonUrl:string};

export const CAMPAIGN_TEMPLATES:Record<CampaignTemplateKey,CampaignTemplate>={
product_approved:{key:"product_approved",label:"Product approved",messageClass:"transactional",productSpecific:true,subject:"{product_name} is now live on BidIndex 🚀",previewText:"Your product is live on BidIndex.",heading:"{product_name} is now live on BidIndex 🚀",body:"Hi {founder_name},\n\nYour product has been approved and is now live on BidIndex. View your listing and share the launch with your audience.\n\n— Shokhrukh Karimov\nBidIndex",includeProductLogo:true,primaryButtonLabel:"Share on X",primaryButtonUrl:"{share_x_url}",secondaryButtonLabel:"View your product",secondaryButtonUrl:"{product_url}"},
founding_product:{key:"founding_product",label:"Founding-product campaign",messageClass:"marketing",productSpecific:false,subject:"A founding-product update for {product_name}",previewText:"Thank you for being part of the beginning.",heading:"{product_name} is part of BidIndex’s founding launch",body:"Hi {founder_name},\n\n{product_name} is one of the early products on BidIndex.\n\nBidIndex has reached {visitor_count} visitors. When you share your listing, your audience can discover and genuinely support your product. Authentic upvotes help your position in the Most Upvoted leaderboard, and every new visitor strengthens the shared audience for all founding products.\n\nThank you for being part of the beginning.\n\n— Shokhrukh Karimov\nBidIndex",includeProductLogo:true,primaryButtonLabel:"Share {product_name} on X",primaryButtonUrl:"{share_x_url}",secondaryButtonLabel:"View your listing",secondaryButtonUrl:"{product_url}"},
visitor_milestone:{key:"visitor_milestone",label:"Visitor milestone",messageClass:"marketing",productSpecific:false,subject:"BidIndex reached 100 visitors — let’s reach 500 🚀",previewText:"Thank you for being part of BidIndex from the beginning.",heading:"We reached our first 100 visitors 🚀",body:"Hi {founder_name},\n\n{product_name} is one of the first 21 products on BidIndex.\n\nWe have already reached our first 100 visitors.\n\nOur next goal is 500. There are 20 other founders on BidIndex. If every founder brings only 20 visitors, we can bring around 400 new visitors and reach 500 together.\n\nWhen you share your listing, people can discover and support your product. Real upvotes can move your product higher in the Most Upvoted leaderboard.\n\nThank you for being part of BidIndex from the beginning.\n\n— Shokhrukh Karimov\nBidIndex",includeProductLogo:true,primaryButtonLabel:"Share your product on X",primaryButtonUrl:"{share_x_url}",secondaryButtonLabel:"View your product",secondaryButtonUrl:"{product_url}"},
verification_reminder:{key:"verification_reminder",label:"Verification reminder",messageClass:"transactional",productSpecific:true,subject:"Verify {product_name} on BidIndex",previewText:"Add the Verified product label and source-labelled traffic.",heading:"Complete product verification",body:"Hi {founder_name},\n\nVerification remains optional and does not affect organic rank. Confirm your domain and install the compact BidIndex badge to receive the Verified product label, eligibility for the Verified section, BidIndex-measured traffic, source-labelled metrics, and a badge linking to your public listing. Revenue and server-event integration remain optional.\n\n— Shokhrukh Karimov\nBidIndex",includeProductLogo:true,primaryButtonLabel:"Open Verification & data",primaryButtonUrl:"{verification_url}",secondaryButtonLabel:"View your listing",secondaryButtonUrl:"{product_url}"},
badge_installation_reminder:{key:"badge_installation_reminder",label:"Badge-installation reminder",messageClass:"transactional",productSpecific:true,subject:"Finish verifying {product_name} on BidIndex",previewText:"Your domain is verified; install the badge to finish.",heading:"Install your BidIndex badge",body:"Hi {founder_name},\n\nYour domain is confirmed. Install the compact BidIndex badge to complete the Verified product status. Verification identifies the product and enables BidIndex-measured traffic with source-labelled metrics; it does not verify revenue or improve organic rank.\n\n— Shokhrukh Karimov\nBidIndex",includeProductLogo:true,primaryButtonLabel:"Install the badge",primaryButtonUrl:"{verification_url}",secondaryButtonLabel:"View your listing",secondaryButtonUrl:"{product_url}"},
weekly_founder_results:{key:"weekly_founder_results",label:"Weekly founder results",messageClass:"marketing",productSpecific:false,subject:"Your BidIndex founder results",previewText:"A compact summary of your product’s results.",heading:"Your BidIndex results",body:"Hi {founder_name},\n\nHere’s how {product_name} is doing:\nProduct views: {product_views}\nGenuine upvotes: {product_upvotes}\nCurrent Most Upvoted rank: #{product_rank}\nReferred BidIndex visitors: {referred_visitors}\n\n— Shokhrukh Karimov\nBidIndex",includeProductLogo:true,primaryButtonLabel:"Share your product on X",primaryButtonUrl:"{share_x_url}",secondaryButtonLabel:"View your listing",secondaryButtonUrl:"{product_url}"},
custom_announcement:{key:"custom_announcement",label:"Custom announcement",messageClass:"marketing",productSpecific:false,subject:"BidIndex update",previewText:"An update from BidIndex.",heading:"A BidIndex update",body:"Hi {founder_name},\n\nWrite your announcement here.\n\n— Shokhrukh Karimov\nBidIndex",includeProductLogo:false,primaryButtonLabel:"View your listing",primaryButtonUrl:"{product_url}",secondaryButtonLabel:"",secondaryButtonUrl:""}
};

export function personalize(value:string,tokens:Partial<PersonalizationValues>):string{return value.replace(/\{([a-z_]+)\}/g,(match,token:string)=>token in tokens?String(tokens[token as PersonalizationToken]??""):match)}
export function unresolvedTokens(value:string):string[]{return [...new Set(Array.from(value.matchAll(/\{([^{}]+)\}/g),item=>item[1]).filter(token=>!(PERSONALIZATION_TOKENS as readonly string[]).includes(token)))]}
export function safeCampaignUrl(value:string,siteUrl:string):string|null{try{const url=new URL(value);if(url.username||url.password)return null;if(url.protocol==="https:")return url.toString();if(process.env.NODE_ENV!=="production"&&url.protocol==="http:"&&url.origin===new URL(siteUrl).origin)return url.toString();return null}catch{return null}}
function escapeHtml(value:string):string{return value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]!)}
export function renderControlledEmail(input:{subject:string;previewText:string;heading:string;body:string;logoUrl?:string|null;primary?:{label:string;url:string}|null;secondary?:{label:string;url:string}|null;preferenceUrl?:string|null}):{html:string;text:string}{const button=(item:{label:string;url:string},primary=false)=>`<a href="${escapeHtml(item.url)}" style="display:inline-block;margin:0 8px 10px 0;padding:13px 18px;border-radius:9px;border:1px solid ${primary?"#ff6154":"#e5e7eb"};background:${primary?"#ff6154":"#fff"};color:${primary?"#fff":"#1f2937"};font-weight:700;text-decoration:none">${escapeHtml(item.label)}</a>`;const paragraphs=input.body.split(/\n{2,}/).map(p=>`<p style="margin:0 0 16px;color:#667085;line-height:1.65">${escapeHtml(p).replaceAll("\n","<br>")}</p>`).join("");const footer=input.preferenceUrl?`<p style="margin:28px 0 0;padding-top:18px;border-top:1px solid #e5e7eb;color:#98a2b3;font-size:12px;line-height:1.5">You are receiving BidIndex founder updates because you opted in. <a href="${escapeHtml(input.preferenceUrl)}" style="color:#667085">Manage email preferences or unsubscribe</a>.</p>`:"";const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:560px){.wrap{padding:14px!important}.card{padding:22px 16px!important}.actions a{display:block!important;margin-right:0!important;text-align:center!important}}</style></head><body style="margin:0;background:#f7f7f8;color:#1f2937;font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"><div style="display:none;max-height:0;overflow:hidden">${escapeHtml(input.previewText)}</div><div class="wrap" style="padding:32px 16px"><div class="card" style="max-width:620px;margin:0 auto;padding:36px;border:1px solid #e5e7eb;border-radius:12px;background:#fff"><div style="margin-bottom:28px;font-size:20px;font-weight:800">BidIndex</div>${input.logoUrl?`<img src="${escapeHtml(input.logoUrl)}" width="64" height="64" alt="Product logo" style="display:block;width:64px;height:64px;margin-bottom:20px;border-radius:13px;object-fit:cover">`:""}<h1 style="margin:0 0 18px;font-size:28px;line-height:1.2">${escapeHtml(input.heading)}</h1>${paragraphs}<div class="actions">${input.primary?button(input.primary,true):""}${input.secondary?button(input.secondary):""}</div>${footer}</div></div></body></html>`;const links=[input.primary,input.secondary].filter(Boolean).map(item=>`\n${item!.label}: ${item!.url}`).join("");return{html,text:`${input.heading}\n\n${input.body}${links}${input.preferenceUrl?`\n\nManage email preferences or unsubscribe: ${input.preferenceUrl}`:""}`}}
