export const CAMPAIGN_TEMPLATE_KEYS=["product_approved","claim_invitation","founding_product","visitor_milestone","verification_reminder","badge_installation_reminder","weekly_founder_results","custom_announcement"] as const;
export type CampaignTemplateKey=typeof CAMPAIGN_TEMPLATE_KEYS[number];
export type MessageClass="transactional"|"marketing";
export const PERSONALIZATION_TOKENS=["founder_name","product_name","product_url","claim_url","share_x_url","visitor_count","product_views","product_upvotes","product_rank","referred_visitors","verification_url"] as const;
export type PersonalizationToken=typeof PERSONALIZATION_TOKENS[number];
export type PersonalizationValues=Record<PersonalizationToken,string>;
export type CampaignTemplate={key:CampaignTemplateKey;label:string;messageClass:MessageClass;productSpecific:boolean;subject:string;previewText:string;heading:string;body:string;includeProductLogo:boolean;primaryButtonLabel:string;primaryButtonUrl:string;secondaryButtonLabel:string;secondaryButtonUrl:string};

export const CAMPAIGN_TEMPLATES:Record<CampaignTemplateKey,CampaignTemplate>={
product_approved:{key:"product_approved",label:"Product approved",messageClass:"transactional",productSpecific:true,subject:"{product_name} is now live on FounderTrail 🚀",previewText:"Your product is live on FounderTrail.",heading:"{product_name} is now live on FounderTrail 🚀",body:"Hi {founder_name},\n\nYour product has been approved and is now live on FounderTrail. View your listing and share the launch with your audience.\n\n— Shokhrukh Karimov\nFounderTrail",includeProductLogo:true,primaryButtonLabel:"Share on X",primaryButtonUrl:"{share_x_url}",secondaryButtonLabel:"View your product",secondaryButtonUrl:"{product_url}"},
claim_invitation:{key:"claim_invitation",label:"Ownership claim invitation",messageClass:"transactional",productSpecific:true,subject:"Claim {product_name} on FounderTrail",previewText:"Review the existing listing and verify that you control its domain.",heading:"Claim the {product_name} listing",body:"Hi {founder_name},\n\nAn existing FounderTrail listing for {product_name} has not yet been linked to a verified owner account. If you own or manage this product, sign in and verify control of its domain to claim the same listing and preserve its history.\n\nThis invitation does not transfer ownership by itself. If domain verification is unavailable, you can request documented manual review. If you are not connected to this product, no action is needed.\n\n— Shokhrukh Karimov\nFounderTrail",includeProductLogo:true,primaryButtonLabel:"Review ownership claim",primaryButtonUrl:"{claim_url}",secondaryButtonLabel:"View the listing",secondaryButtonUrl:"{product_url}"},
founding_product:{key:"founding_product",label:"Early-product campaign",messageClass:"marketing",productSpecific:false,subject:"An early FounderTrail update for {product_name}",previewText:"Thank you for helping build the early directory.",heading:"Thank you for building with FounderTrail",body:"Hi {founder_name},\n\n{product_name} is part of FounderTrail’s early directory. Its existing profile and historical support remain intact as we add launches, discussions, follows, and founder updates.\n\nShare the product only when it is useful to your audience; paid promotion and historical support never affect weekly launch order.\n\n— Shokhrukh Karimov\nFounderTrail",includeProductLogo:true,primaryButtonLabel:"Share {product_name} on X",primaryButtonUrl:"{share_x_url}",secondaryButtonLabel:"View your listing",secondaryButtonUrl:"{product_url}"},
visitor_milestone:{key:"visitor_milestone",label:"Visitor milestone",messageClass:"marketing",productSpecific:false,subject:"A FounderTrail community update",previewText:"A measured update from the FounderTrail directory.",heading:"The FounderTrail community is growing",body:"Hi {founder_name},\n\nFounderTrail has recorded {visitor_count} daily visitor entries across the directory. This is an operational measurement, not a claim about customers delivered.\n\nYou can keep {product_name} useful by answering questions and publishing meaningful product updates. Sharing is always optional.\n\n— Shokhrukh Karimov\nFounderTrail",includeProductLogo:true,primaryButtonLabel:"View your product",primaryButtonUrl:"{product_url}",secondaryButtonLabel:"",secondaryButtonUrl:""},
verification_reminder:{key:"verification_reminder",label:"Tracker setup reminder",messageClass:"transactional",productSpecific:true,subject:"Optional tracking setup for {product_name}",previewText:"Connect source-labelled site traffic if you choose.",heading:"Complete the optional site tracker",body:"Hi {founder_name},\n\nThe site tracker is optional and does not affect ownership, approval, or launch rank. Confirm the domain and install the compact FounderTrail badge only if you want FounderTrail-measured site traffic and a badge linking to your public listing. Revenue and server-event connections remain separate and optional.\n\n— Shokhrukh Karimov\nFounderTrail",includeProductLogo:true,primaryButtonLabel:"Open Verification & data",primaryButtonUrl:"{verification_url}",secondaryButtonLabel:"View your listing",secondaryButtonUrl:"{product_url}"},
badge_installation_reminder:{key:"badge_installation_reminder",label:"Badge-installation reminder",messageClass:"transactional",productSpecific:true,subject:"Finish the optional tracker for {product_name}",previewText:"Your domain check passed; install the badge to activate tracking.",heading:"Install your optional FounderTrail badge",body:"Hi {founder_name},\n\nYour tracker domain check passed. Install the compact FounderTrail badge only if you want to activate FounderTrail-measured traffic. The badge does not verify revenue, ownership, or product quality and does not improve organic launch order.\n\n— Shokhrukh Karimov\nFounderTrail",includeProductLogo:true,primaryButtonLabel:"Install the badge",primaryButtonUrl:"{verification_url}",secondaryButtonLabel:"View your listing",secondaryButtonUrl:"{product_url}"},
weekly_founder_results:{key:"weekly_founder_results",label:"Founder activity summary",messageClass:"marketing",productSpecific:false,subject:"Your FounderTrail product activity",previewText:"A compact summary of measured product activity.",heading:"Your FounderTrail activity",body:"Hi {founder_name},\n\nHere’s the historical activity currently associated with {product_name}:\nQualified profile views: {product_views}\nLegacy support total: {product_upvotes}\nHistorical referred visitors: {referred_visitors}\n\nThe historical figures are kept for continuity and do not determine a FounderTrail launch rank.\n\n— Shokhrukh Karimov\nFounderTrail",includeProductLogo:true,primaryButtonLabel:"View your listing",primaryButtonUrl:"{product_url}",secondaryButtonLabel:"",secondaryButtonUrl:""},
custom_announcement:{key:"custom_announcement",label:"Custom announcement",messageClass:"marketing",productSpecific:false,subject:"FounderTrail update",previewText:"An update from FounderTrail.",heading:"A FounderTrail update",body:"Hi {founder_name},\n\nWrite your announcement here.\n\n— Shokhrukh Karimov\nFounderTrail",includeProductLogo:false,primaryButtonLabel:"View your listing",primaryButtonUrl:"{product_url}",secondaryButtonLabel:"",secondaryButtonUrl:""}
};

export function personalize(value:string,tokens:Partial<PersonalizationValues>):string{return value.replace(/\{([a-z_]+)\}/g,(match,token:string)=>token in tokens?String(tokens[token as PersonalizationToken]??""):match)}
export function unresolvedTokens(value:string):string[]{return [...new Set(Array.from(value.matchAll(/\{([^{}]+)\}/g),item=>item[1]).filter(token=>!(PERSONALIZATION_TOKENS as readonly string[]).includes(token)))]}
export function safeCampaignUrl(value:string,siteUrl:string):string|null{try{const url=new URL(value);if(url.username||url.password)return null;if(url.protocol==="https:")return url.toString();if(process.env.NODE_ENV!=="production"&&url.protocol==="http:"&&url.origin===new URL(siteUrl).origin)return url.toString();return null}catch{return null}}
function escapeHtml(value:string):string{return value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]!)}
export function renderControlledEmail(input:{subject:string;previewText:string;heading:string;body:string;logoUrl?:string|null;primary?:{label:string;url:string}|null;secondary?:{label:string;url:string}|null;preferenceUrl?:string|null}):{html:string;text:string}{const button=(item:{label:string;url:string},primary=false)=>`<a href="${escapeHtml(item.url)}" style="display:inline-block;margin:0 8px 10px 0;padding:13px 18px;border-radius:9px;border:1px solid ${primary?"#ff6154":"#e5e7eb"};background:${primary?"#ff6154":"#fff"};color:${primary?"#fff":"#1f2937"};font-weight:700;text-decoration:none">${escapeHtml(item.label)}</a>`;const paragraphs=input.body.split(/\n{2,}/).map(p=>`<p style="margin:0 0 16px;color:#667085;line-height:1.65">${escapeHtml(p).replaceAll("\n","<br>")}</p>`).join("");const footer=input.preferenceUrl?`<p style="margin:28px 0 0;padding-top:18px;border-top:1px solid #e5e7eb;color:#98a2b3;font-size:12px;line-height:1.5">You are receiving FounderTrail founder updates because you opted in. <a href="${escapeHtml(input.preferenceUrl)}" style="color:#667085">Manage email preferences or unsubscribe</a>.</p>`:"";const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:560px){.wrap{padding:14px!important}.card{padding:22px 16px!important}.actions a{display:block!important;margin-right:0!important;text-align:center!important}}</style></head><body style="margin:0;background:#f7f7f8;color:#1f2937;font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"><div style="display:none;max-height:0;overflow:hidden">${escapeHtml(input.previewText)}</div><div class="wrap" style="padding:32px 16px"><div class="card" style="max-width:620px;margin:0 auto;padding:36px;border:1px solid #e5e7eb;border-radius:12px;background:#fff"><div style="margin-bottom:28px;font-size:20px;font-weight:800">FounderTrail</div>${input.logoUrl?`<img src="${escapeHtml(input.logoUrl)}" width="64" height="64" alt="Product logo" style="display:block;width:64px;height:64px;margin-bottom:20px;border-radius:13px;object-fit:cover">`:""}<h1 style="margin:0 0 18px;font-size:28px;line-height:1.2">${escapeHtml(input.heading)}</h1>${paragraphs}<div class="actions">${input.primary?button(input.primary,true):""}${input.secondary?button(input.secondary):""}</div>${footer}</div></div></body></html>`;const links=[input.primary,input.secondary].filter(Boolean).map(item=>`\n${item!.label}: ${item!.url}`).join("");return{html,text:`${input.heading}\n\n${input.body}${links}${input.preferenceUrl?`\n\nManage email preferences or unsubscribe: ${input.preferenceUrl}`:""}`}}
