import { NextResponse } from "next/server";
import { withTransaction } from "@/lib/db";
import { authenticateOwner } from "@/lib/owner-auth";
import { hashIntegrationSecret, newIntegrationSecret, newVerificationToken } from "@/lib/integration-security";
import { requestOriginIsSameSite } from "@/lib/request-security";

export async function POST(request:Request,context:RouteContext<"/api/owner/products/[slug]/integration">){
  if(!requestOriginIsSameSite(request))return NextResponse.json({error:"Invalid origin."},{status:403});const {slug}=await context.params;const owner=await authenticateOwner(request,slug);if(!owner)return NextResponse.json({error:"Owner access required."},{status:401});const body=await request.json().catch(()=>({})) as {action?:unknown};const action=body.action==="rotate"?"rotate":"create";const secret=newIntegrationSecret();
  try{const result=await withTransaction(async(client)=>{const product=await client.query<{normalized_domain:string}>(`SELECT normalized_domain FROM products WHERE id=$1::uuid`,[owner.productId]);const domain=product.rows[0]?.normalized_domain;if(!domain)throw new Error("NOT_FOUND");const existing=await client.query<{public_id:string}>(`SELECT public_id::text FROM product_integrations WHERE product_id=$1::uuid`,[owner.productId]);if(existing.rows[0]){if(action!=="rotate")return {publicId:existing.rows[0].public_id,secret:null};await client.query(`UPDATE product_integrations SET secret_hash=$2,secret_version=secret_version+1,updated_at=now() WHERE product_id=$1::uuid`,[owner.productId,hashIntegrationSecret(secret)]);return {publicId:existing.rows[0].public_id,secret};}const inserted=await client.query<{public_id:string}>(`INSERT INTO product_integrations (product_id,allowed_domain,secret_hash,verification_token) VALUES ($1::uuid,$2,$3,$4) RETURNING public_id::text`,[owner.productId,domain,hashIntegrationSecret(secret),newVerificationToken()]);return {publicId:inserted.rows[0].public_id,secret};});return NextResponse.json({...result,message:result.secret?"Copy this server secret now; it will not be shown again.":"Integration already exists."},{status:result.secret?201:200});}catch(error){console.error("integration setup failed",error instanceof Error?error.message:"unknown");return NextResponse.json({error:"Could not configure the integration."},{status:500});}
}
